import type { NextPage } from "next";
import Head from "next/head";
import Header from "@/components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Create next app</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h1>
          welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur,
          corrupti.
        </p>
      </main>
    </>
  );
};

export default Home;
