import type { NextPage } from "next";
import Head from "next/head";
import Header from "@/components/Header";
import { Button, Container } from "reactstrap";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title> Create next app</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="py-5 text-center">
          <h1>O melhor jeito de comprar o que você ama</h1>
          <p className="my-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero,
            libero!
          </p>
          <Link href="/products">
            <Button color="dark" className="px-4 pb-2">
              Conheça nossos produos!
            </Button>
          </Link>
        </Container>
      </main>
    </>
  );
};

export default Home;
